apiVersion: apps/v1
kind: Deployment
metadata:
  name: santander-dockercoins-hasher-deploy
spec:
  selector:
    matchLabels:
      app: santander-dockercoins-hasher
  replicas: 3
  template:
    metadata:
      labels:
        app: santander-dockercoins-hasher
    spec:
      containers:
        - name: santander-dockercoins-hasher-container
          args:
            - hasher.rb
          command:
            - irb
          image: ganimedescolomar/santander-dockercoins:1.1-hasher
          volumeMounts:
            -
              mountPath: /src/
              name: santander-dockercoins-hasher-volume
              readOnly: true
          workingDir: /src/
      initContainers:
        -
          name: santander-dockercoins-hasher-initcontainer
          args:
            - -c
            - set -x; cd /src/; git clone https://github.com/ganimedes-colomar/santander-dockercoins.git; cd santander-dockercoins; git checkout docker210621; cp hasher/hasher.rb /src/; rm -rf /src/santander-dockercoins;
          command:
            - sh
          image: alpine/git:latest
          volumeMounts:
            -
              mountPath: /src/
              name: santander-dockercoins-hasher-volume
              readOnly: false
      volumes:
        -
          name: santander-dockercoins-hasher-volume
          emptyDir: {}
