apiVersion: apps/v1
kind: Deployment
metadata:
  name: santander-dockercoins-rng-deploy
spec:
  selector:
    matchLabels:
      app: santander-dockercoins-rng
  replicas: 3
  template:
    metadata:
      labels:
        app: santander-dockercoins-rng
    spec:
      containers:
        - name: santander-dockercoins-rng-container
          args:
            - rng.py
          command:
            - python
          image: ganimedescolomar/santander-dockercoins:1.1-rng
          volumeMounts:
            -
              mountPath: /src/
              name: santander-dockercoins-rng-volume
              readOnly: true
          workingDir: /src/
      initContainers:
        -
          name: santander-dockercoins-rng-initcontainer
          args:
            - -c
            - cd /src/; git clone https://github.com/ganimedes-colomar/santander-dockercoins.git; cd santander-dockercoins; git checkout docker210621; cp rng/rng.py /src/; rm -rf /src/santander-dockercoins;
          command:
            - sh
          image: alpine/git:latest
          volumeMounts:
            -
              mountPath: /src/
              name: santander-dockercoins-rng-volume
              readOnly: false
      volumes:
        -
          name: santander-dockercoins-rng-volume
          emptyDir: {}
