apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-label
  template:
    metadata:
      labels:
        app: worker-label
    spec:
      containers:
        -
          image: ganimedescolomar/santander-dockercoins:latest-worker
          name: worker-container
          ports:
            - containerPort: 8080
