name: CI
on:
        push:
                branches:
                -
                        docker210621
jobs:
        docker:
                runs-on: ubuntu-18.04
                steps:
                -
                        name: checkout
                        uses: actions/checkout@v2
                -
                        name: docker build
                        run: |
                                for app in hasher rng webui worker; do
                                        docker build -t ${app} -f ${app}/Dockerfile .;
                                done;
                -
                        name: docker network create
                        run: |
                                for app in hasher redis rng webui worker; do
                                        docker network create ${app};
                                done;
                -
                        name: docker run redis
                        run: docker run -d --rm --network redis-network --name redis -v redis-volume:/data -w /data --entrypoint docker-entrypoint.sh redis:6.2.4-alpine3.13@sha256:b7cb70118c9729f8dc019187a4411980418a87e6a837f4846e87130df379e2c8 redis-server;
                -
                        name: docker run hasher
                        run: docker run -d --rm --network hasher-network --name hasher -v $PWD/hasher/:/src/:ro -w /src --entrypoint ruby hasher hasher.rb
                -
                        name: docker run rng
                        run: docker run -d --rm --network rng-network --name rng --entrypoint python -v $PWD/rng/:/src/:ro -w /src rng rng.py
                -
                        name: docker run worker
                        run: docker run -d --rm --network worker-network --name worker --entrypoint python -v $PWD/worker/:/src/:ro -w /src worker worker.py
                -
                        name: docker run webui
                        run: docker run -d --rm --network webui-network --name webui --entrypoint node -v $PWD/webui/:/src/:ro -w /src webui webui.js
                -
                        name: docker network connect redis
                        run: |
                                for app in webui worker; do
                                        docker network connect redis ${app};
                                done;
                -
                        name: docker network connect
                        run: |
                                for network in hasher rng; do
                                        docker network connect ${network} worker;
                                done;
                -
                        name: docker logs hasher
                        run: |
                                while true; do
                                        docker logs hasher 2>&1 \
                                        | grep '== Sinatra .* has taken the stage on .* for development with backup from Thin' \
                                                && break;
                                        sleep 10;
                                done;
                -
                        name: docker logs redis
                        run: |
                                while true; do
                                        docker logs redis 2>&1 \
                                        | grep 'Ready to accept connections' \
                                                && break;
                                        sleep 10;
                                done;
                -
                        name: docker logs rng
                        run: |
                                while true; do
                                        docker logs rng 2>&1 \
                                        | grep 'Running on' \
                                                && break;
                                        sleep 10;
                                done;
                -
                        name: docker logs webui
                        run: |
                                while true; do
                                        docker logs webui 2>&1 \
                                        | grep 'WEBUI running on port' \
                                                && break;
                                        sleep 10;
                                done;
                -
                        name: docker logs worker
                        run: |
                                while true; do
                                        docker logs worker 2>&1 \
                                        | grep 'Coin found' \
                                                && break;
                                        sleep 10;
                                done;
